package bmwcardata

// Code generated by github.com/tjamet/bmw-cardata/cmd/generate. DO NOT EDIT.
var (
	mqttReasonCodes = map[ReasonCode]MQTTReasonCode{
		ReasonCode(0x00): MQTTReasonCode{
			Name: "Granted QoS 0",
			Packets: []string{
				"SUBACK",
			},
			Details: "0, 1, and 2 in the SUBACK packet are used to indicate the subscription result. They all represent a successful subscription, and at the same time, they indicate the maximum QoS level granted to the subscriber. 0, 1, and 2 exactly correspond to three QoS levels.This is because the maximum QoS level granted by the server may be smaller than the maximum QoS level requested when subscribing. For example, if the maximum QoS level requested during subscription is 2, but the server only supports QoS 1, etc.",
		},
		ReasonCode(0x01): MQTTReasonCode{
			ReasonCode: ReasonCode(0x01),
			Name:       "Granted QoS 1",
			Packets: []string{
				"SUBACK",
			},
			Details: "-",
		},
		ReasonCode(0x02): MQTTReasonCode{
			ReasonCode: ReasonCode(0x02),
			Name:       "Granted QoS 2",
			Packets: []string{
				"SUBACK",
			},
			Details: "-",
		},
		ReasonCode(0x04): MQTTReasonCode{
			ReasonCode: ReasonCode(0x04),
			Name:       "Disconnect with Will Message",
			Packets: []string{
				"DISCONNECT",
			},
			Details: "Only used for DISCONNECT packets, and it is suitable for situations where the client wants to disconnect normally, but the server still needs to publish a will message. For example, the clients want to be notified of session expiration.",
		},
		ReasonCode(0x10): MQTTReasonCode{
			ReasonCode: ReasonCode(0x10),
			Name:       "No matching subscribers",
			Packets: []string{
				"PUBACK",
				"PUBREC",
			},
			Details: "This Reason Code is used to indicate to the sender that the message has been received, but there are currently no matching subscribers, so only the server can use this Reason Code. We can know that no one will receive our message when we receive a response packet with Reason Code 0x10, but we cannot assume that everyone will receive our message when we do not receive a response packet with Reason Code 0x10, unless there will be at most one subscriber. But note that using 0x10 instead of 0x00 when there are no matching subscribers is not a mandatory behavior, it depends on the specific implementation of the server.",
		},
		ReasonCode(0x11): MQTTReasonCode{
			ReasonCode: ReasonCode(0x11),
			Name:       "No subscription existed",
			Packets: []string{
				"UNSUBACK",
			},
			Details: "Only used for UNSUBACK packets, indicating that no matching subscription was found when unsubscribing.",
		},
		ReasonCode(0x18): MQTTReasonCode{
			ReasonCode: ReasonCode(0x18),
			Name:       "Continue authentication",
			Packets: []string{
				"AUTH",
			},
			Details: "Only used for AUTH packets, indicating to continue authentication. Through this Reason Code, the client and server can exchange AUTH packets any number of times to meet the needs of different authentication methods.",
		},
		ReasonCode(0x19): MQTTReasonCode{
			ReasonCode: ReasonCode(0x19),
			Name:       "Re-authenticate",
			Packets: []string{
				"AUTH",
			},
			Details: "Only used for AUTH packets. After enhanced authentication is successful, the client can initiate re-authentication at any time by sending an AUTH packet with Reason Code 0x19. During re-authentication, other packet sending and receiving will continue normally. If re-authentication fails, the connection will be closed.",
		},
		ReasonCode(0x80): MQTTReasonCode{
			ReasonCode: ReasonCode(0x80),
			Name:       "Unspecified error",
			Packets: []string{
				"CONNACK",
				"PUBACK",
				"PUBREC",
				"SUBACK",
				"UNSUBACK",
				"DISCONNECT",
			},
			Details: "Indicates an unspecified error. When one party does not wish to disclose the specific cause of the error to the other party, or no Reason Code can match the current situation in the protocol specification, it can use this Reason Code in the packet.",
		},
		ReasonCode(0x81): MQTTReasonCode{
			ReasonCode: ReasonCode(0x81),
			Name:       "Malformed Packet",
			Packets: []string{
				"CONNACK",
				"DISCONNECT",
			},
			Details: "Indicates that the received packet cannot be correctly parsed according to the protocol specifications. In MQTT, we refer to these types of packets as malformed packets.",
		},
		ReasonCode(0x82): MQTTReasonCode{
			ReasonCode: ReasonCode(0x82),
			Name:       "Protocol Error",
			Packets: []string{
				"CONNACK",
				"DISCONNECT",
			},
			Details: "Protocol errors usually refer to errors that can be discovered only after the control packet is parsed according to the protocol specifications, including data that the protocol does not allow, behavior that does not conform to the protocol requirements, and so on. For example, the client sends two CONNECT packets within a single connection.",
		},
		ReasonCode(0x83): MQTTReasonCode{
			ReasonCode: ReasonCode(0x83),
			Name:       "Implementation specific error",
			Packets: []string{
				"CONNACK",
				"PUBACK",
				"PUBREC",
				"SUBACK",
				"UNSUBACK",
				"DISCONNECT",
			},
			Details: "The packet is valid, but not accepted by the current receiver's implementation.",
		},
		ReasonCode(0x84): MQTTReasonCode{
			ReasonCode: ReasonCode(0x84),
			Name:       "Unsupported Protocol Version",
			Packets: []string{
				"CONNACK",
			},
			Details: "Only used for CONNACK packets, indicating that the server does not support the MQTT protocol version requested by the client.",
		},
		ReasonCode(0x85): MQTTReasonCode{
			ReasonCode: ReasonCode(0x85),
			Name:       "Client Identifier not valid",
			Packets: []string{
				"CONNACK",
			},
			Details: "Only used for CONNACK packets, indicating that the Client ID is valid, but is not accepted by the server. For example, the Client ID exceeds the maximum length allowed by the server.",
		},
		ReasonCode(0x86): MQTTReasonCode{
			ReasonCode: ReasonCode(0x86),
			Name:       "Bad User Name or Password",
			Packets: []string{
				"CONNACK",
			},
			Details: "Only used for CONNACK packets, indicating that the client was refused a connection because it used an incorrect username or password.",
		},
		ReasonCode(0x87): MQTTReasonCode{
			ReasonCode: ReasonCode(0x87),
			Name:       "Not authorized",
			Packets: []string{
				"CONNACK",
				"PUBACK",
				"PUBREC",
				"SUBACK",
				"UNSUBACK",
				"DISCONNECT",
			},
			Details: "Indicates that the operation is not authorized. For example, the client does not have permission to publish messages to the corresponding topic.",
		},
		ReasonCode(0x88): MQTTReasonCode{
			ReasonCode: ReasonCode(0x88),
			Name:       "Server unavailable",
			Packets: []string{
				"CONNACK",
			},
			Details: "Only used for CONNACK packets, indicating to the client that the server is currently unavailable. For example, the current server authentication service is abnormal and cannot accept new clients.",
		},
		ReasonCode(0x89): MQTTReasonCode{
			ReasonCode: ReasonCode(0x89),
			Name:       "Server busy",
			Packets: []string{
				"CONNACK",
				"DISCONNECT",
			},
			Details: "Indicates to the client that the server is busy, please try again later.",
		},
		ReasonCode(0x8A): MQTTReasonCode{
			ReasonCode: ReasonCode(0x8A),
			Name:       "Banned",
			Packets: []string{
				"CONNACK",
			},
			Details: "Only used for CONNACK packets, indicating that the client is banned from logging in. For example, the server detects abnormal connection behavior from the client, so it adds the client's Client ID or IP address to the blacklist, or the background administrator manually bans the client. Of course, these usually depend on the specific implementation of the server.",
		},
		ReasonCode(0x8B): MQTTReasonCode{
			ReasonCode: ReasonCode(0x8B),
			Name:       "Server shutting down",
			Packets: []string{
				"DISCONNECT",
			},
			Details: "Only used for DISCONNECT packets, and only the server can use it. If the server is in the process of or about to shut down, it can inform the client that the connection is terminated because the server is shutting down by actively sending a DISCONNECT packet with Reason Code 0x8B. This can help clients avoid continuing to initiate connection requests to this server after the connection is closed.",
		},
		ReasonCode(0x8C): MQTTReasonCode{
			ReasonCode: ReasonCode(0x8C),
			Name:       "Bad authentication method",
			Packets: []string{
				"CONNACK",
				"DISCONNECT",
			},
			Details: "When the server does not support the enhanced authentication method specified by the client, or the client uses a different authentication method than the previous authentication during re-authentication, the server will send a CONNACK or DISCONNECT packet with Reason Code 0x8C.",
		},
		ReasonCode(0x8D): MQTTReasonCode{
			ReasonCode: ReasonCode(0x8D),
			Name:       "Keep Alive timeout",
			Packets: []string{
				"DISCONNECT",
			},
			Details: "Only used for DISCONNECT packets, and only the server can use it. The server closed the connection because it did not receive any packets within 1.5 times the Keep Alive time.",
		},
		ReasonCode(0x8E): MQTTReasonCode{
			ReasonCode: ReasonCode(0x8E),
			Name:       "Session taken over",
			Packets: []string{
				"DISCONNECT",
			},
			Details: "Only used for DISCONNECT packets, and only the server can use it. Another more recent connection using the same Client ID was established, causing the server to close this connection.",
		},
		ReasonCode(0x8F): MQTTReasonCode{
			ReasonCode: ReasonCode(0x8F),
			Name:       "Topic Filter invalid",
			Packets: []string{
				"SUBACK",
				"UNSUBACK",
				"DISCONNECT",
			},
			Details: "The Topic Filter is in the correct format, but is not accepted by the server. For example, the level of Topic Filters exceeds the maximum number allowed by the server.",
		},
		ReasonCode(0x90): MQTTReasonCode{
			ReasonCode: ReasonCode(0x90),
			Name:       "Topic Name invalid",
			Packets: []string{
				"PUBACK",
				"PUBREC",
				"DISCONNECT",
			},
			Details: "The Topic Name is in the correct format, but is not accepted by the client or server.",
		},
		ReasonCode(0x91): MQTTReasonCode{
			ReasonCode: ReasonCode(0x91),
			Name:       "Packet identifier in use",
			Packets: []string{
				"PUBACK",
				"PUBREC",
				"SUBACK",
				"UNSUBACK",
				"DISCONNECT",
			},
			Details: "The Packet ID in the received packet is in use. This usually means that the session state of the client and server do not match, or that one of them has an incorrect implementation.",
		},
		ReasonCode(0x92): MQTTReasonCode{
			ReasonCode: ReasonCode(0x92),
			Name:       "Packet Identifier not found",
			Packets: []string{
				"PUBREL",
				"PUBCOMP",
			},
			Details: "Only used for PUBREL and PUBCOMP packets, indicating that the Packet ID in the received packet is not found. This usually means that the session state of the client and server do not match, or that one of them has an incorrect implementation.",
		},
		ReasonCode(0x93): MQTTReasonCode{
			ReasonCode: ReasonCode(0x93),
			Name:       "Receive Maximum exceeded",
			Packets: []string{
				"DISCONNECT",
			},
			Details: "Only used for DISCONNECT packets, indicating that the maximum receive value has been exceeded. MQTT 5.0 adds a flow control mechanism. When connecting, the client and server agree on the number of reliable messages that can be processed simultaneously through the Receive Maximum property (QoS > 0). Therefore, when the number of unconfirmed messages sent by the sender exceeds this limit, the receiver will send a DISCONNECT packet with Reason Code 0x93 and close the network connection.",
		},
		ReasonCode(0x94): MQTTReasonCode{
			ReasonCode: ReasonCode(0x94),
			Name:       "Topic Alias invalid",
			Packets: []string{
				"DISCONNECT",
			},
			Details: "Only used for DISCONNECT packets, indicating that the Topic Alias is invalid. If the Topic Alias value in the PUBLISH packet is 0 or greater than the maximum Topic Alias agreed upon at the time of connection, the receiver will consider this a protocol error and send a DISCONNECT packet with Reason Code 0x94 and close the network connection.",
		},
		ReasonCode(0x95): MQTTReasonCode{
			ReasonCode: ReasonCode(0x95),
			Name:       "Packet too large",
			Packets: []string{
				"CONNACK",
				"DISCONNECT",
			},
			Details: "The packet exceeds the maximum allowable size agreed upon at the time of connection.",
		},
		ReasonCode(0x96): MQTTReasonCode{
			ReasonCode: ReasonCode(0x96),
			Name:       "Message rate too high",
			Packets: []string{
				"DISCONNECT",
			},
			Details: "Only used for DISCONNECT packets, indicating that the message rate is too high. The server may limit the message rate of the client, for example, allowing a maximum of 100 messages per second. When the client exceeds this limit, the server will send a DISCONNECT packet with Reason Code 0x96 and close the network connection.",
		},
		ReasonCode(0x97): MQTTReasonCode{
			ReasonCode: ReasonCode(0x97),
			Name:       "Quota exceeded",
			Packets: []string{
				"CONNACK",
				"PUBACK",
				"PUBREC",
				"SUBACK",
				"DISCONNECT",
			},
			Details: "Used to indicate that a quota limit has been exceeded. The server may limit the sending quota of the publisher, such as allowing a maximum of 1000 messages to be forwarded daily. When the publisher exhausts the quota, the server will use this Reason Code in acknowledgment packets such as PUBACK to remind the publisher. On the other hand, the server may also limit the number of connections and subscriptions of the client. When this limit is exceeded, the server will indicate to the client through CONNACK or SUBACK packets that the current quota has been exceeded. Some strict clients and servers may choose to send a DISCONNECT packet and close the connection when they detect that the peer has exceeded the quota.",
		},
		ReasonCode(0x98): MQTTReasonCode{
			ReasonCode: ReasonCode(0x98),
			Name:       "Administrative action",
			Packets: []string{
				"DISCONNECT",
			},
			Details: "Only used for DISCONNECT packets, indicating to the client that the connection was closed due to a management operation, such as an administrator kicking out the client connection in the background.",
		},
		ReasonCode(0x99): MQTTReasonCode{
			ReasonCode: ReasonCode(0x99),
			Name:       "Payload format invalid",
			Packets: []string{
				"PUBACK",
				"PUBREC",
				"DISCONNECT",
			},
			Details: "Indicates that the format of the Payload does not match the format indicated by the Payload Format Indicator property.",
		},
		ReasonCode(0x9A): MQTTReasonCode{
			ReasonCode: ReasonCode(0x9A),
			Name:       "Retain not supported",
			Packets: []string{
				"CONNACK",
				"DISCONNECT",
			},
			Details: "The server does not support retained messages.",
		},
		ReasonCode(0x9B): MQTTReasonCode{
			ReasonCode: ReasonCode(0x9B),
			Name:       "QoS not supported",
			Packets: []string{
				"CONNACK",
				"DISCONNECT",
			},
			Details: "The server does not support the QoS level requested by the client.",
		},
		ReasonCode(0x9C): MQTTReasonCode{
			ReasonCode: ReasonCode(0x9C),
			Name:       "Use another server",
			Packets: []string{
				"CONNACK",
				"DISCONNECT",
			},
			Details: "The server is temporarily unable to serve the client, and the client should try to connect to another server.",
		},
		ReasonCode(0x9D): MQTTReasonCode{
			ReasonCode: ReasonCode(0x9D),
			Name:       "Server moved",
			Packets: []string{
				"CONNACK",
				"DISCONNECT",
			},
			Details: "The server has moved to another address, and the client should try to connect to the new address.",
		},
		ReasonCode(0x9E): MQTTReasonCode{
			ReasonCode: ReasonCode(0x9E),
			Name:       "Shared Subscriptions not supported",
			Packets: []string{
				"SUBACK",
				"DISCONNECT",
			},
			Details: "The server does not support shared subscriptions.",
		},
		ReasonCode(0x9F): MQTTReasonCode{
			ReasonCode: ReasonCode(0x9F),
			Name:       "Connection rate exceeded",
			Packets: []string{
				"CONNACK",
				"DISCONNECT",
			},
			Details: "The server has exceeded the maximum number of connections it can handle, and the client should try to connect to another server.",
		},
		ReasonCode(0xA0): MQTTReasonCode{
			ReasonCode: ReasonCode(0xA0),
			Name:       "Maximum connect time",
			Packets: []string{
				"DISCONNECT",
			},
			Details: "Only used for DISCONNECT packets, and only the server can use it. For security reasons, the server can limit the maximum connection time of the client for a single authentication. For example, when using JWT authentication, the client connection should not continue after the JWT expires. In this case, the server can send a DISCONNECT packet with Reason Code 0xA0 to indicate to the client that the connection was closed because the maximum allowed connection time has been exceeded. After receiving a DISCONNECT packet with this Reason Code, the client can re-obtain the authentication credentials and request a connection again.",
		},
		ReasonCode(0xA1): MQTTReasonCode{
			ReasonCode: ReasonCode(0xA1),
			Name:       "Subscription Identifiers not supported",
			Packets: []string{
				"SUBACK",
				"DISCONNECT",
			},
			Details: "The server does not support subscription identifiers, but the client's subscription request contains subscription identifiers. The server can either reject the subscription request by sending a SUBACK packet with Reason Code 0xA1, or directly send a DISCONNECT packet with Reason Code 0xA1 and close the network connection.",
		},
		ReasonCode(0xA2): MQTTReasonCode{
			ReasonCode: ReasonCode(0xA2),
			Name:       "Wildcard Subscriptions not supported",
			Packets: []string{
				"SUBACK",
				"DISCONNECT",
			},
			Details: "The server does not support wildcard subscriptions.",
		},
	}
)
